### ISSUE TITLE
haml issue in rails 4

### ISSUE THREAD

**Issue by eashman** [kendrikat/grape-swagger-ui#4]
To make this work on Rails 4.0 with the latest grape/swagger etc., I needed to add 

gem 'haml-rails'

to the Gemfile or else it would kick back an error about not being able to find the templates.

**Comment by kendrikat** [comment]
Dep has been removed completely. So it will work now.

**Comment by kendrikat** [comment]
https://github.com/kendrikat/grape-swagger-ui/commit/0862dd3970728994f5c75172d7ff103c8ad45323
