### ISSUE TITLE
Routing not working

### ISSUE THREAD

**Issue by Chrisissorry** [kendrikat/grape-swagger-ui#6]
When I run `rake routes` it shows me the correct route:

    api_swagger GET          /api/swagger(.:format)                                    swagger#index

However, in the browser it only says not found. I think this is due to lots of custom rules in the project. Where can I start debugging?

**Comment by kendrikat** [comment]
Try to set it higher in routes.rb

**Comment by kendrikat** [comment]
Fell free to reopen if problem still exists.
